---
- name: Test become functionality
  hosts: all
  tasks:
    - name: do a task only root can do
      shell: ls /root
      register: output
    - name: show contents
      debug:
        var: output
